application: goagentmonitor
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /start_fetch
  script: fetch_handler.app
  login: admin

- url: /api/?.*
  script: api_handler.app

